# -*- coding: utf-8 -*-
"""client.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SSHZpX52qOhl7O6RuWEIyypPti9_c3-R
"""

import socket

s = socket.socket()
port = 3125
s.connect(('localhost', port))
z = 'Welcome to Manipal'
s.sendall(z.encode())    
s.close()