# -*- coding: utf-8 -*-
"""server.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SKUIoBRa2_GGuOcZQBslWaBZUCZXzl8m
"""

import socket
import sys

ser = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
port = 3125
ser.bind(('0.0.0.0', port))
print ('Socket binded to port 3125')
ser.listen(3)
print ('socket is listening')

while True:
    cl, addr = ser.accept()
    print ('Got connection from ', addr)
    print (cl.recv(1024))
    cl.close()